# Generated by Django 2.2.5 on 2019-10-09 05:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_order_items_orders_user_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='nickname',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='otime',
            field=models.CharField(max_length=100),
        ),
    ]
