# Generated by Django 2.2.5 on 2019-10-10 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20191009_1359'),
        ('main', '0010_orders_nickname'),
    ]

    operations = [
    ]
