CREATE TABLE `user` (
	`uid` INT UNSIGNED AUTO_INCREMENT,
	`uname` VARCHAR(255) NOT NULL UNIQUE,
	`passwd` VARCHAR(50) NOT NULL,
	`phone` CHAR(11) NOT NULL,
	`email` varchar(255) NOT NULL,
	PRIMARY KEY (`uid`)
) ENGINE=INNODB AUTO_INCREMENT=1000 DEFAULT CHARACTER SET utf8; 



CREATE TABLE `foods` (
	`fid` INT UNSIGNED AUTO_INCREMENT,
	`fname` VARCHAR(255) NOT NULL UNIQUE,
	`price` VARCHAR(50) NOT NULL,
	`size` CHAR(11) NOT NULL,
    `number` INT(50) NOT NULL,
    `type` VARCHAR(30) NOT NULL,
	`img_path` VARCHAR(255) NOT NULL,
	PRIMARY KEY (`fid`)
) ENGINE=INNODB AUTO_INCREMENT=1000 DEFAULT CHARACTER SET utf8; 

CREATE TABLE `orders` (
	`order_id` INT UNSIGNED AUTO_INCREMENT UNIQUE,
	`time` date NOT NULL,
    `customer` VARCHAR(50) NOT NULL,
    `total_money` DECIMAL(8,2) NOT NULL,
	`target_addr` VARCHAR(255) NOT NULL,
	PRIMARY KEY (`order_id`)
) ENGINE=INNODB AUTO_INCREMENT=1000 DEFAULT CHARACTER SET utf8; 


CREATE TABLE `order_items` (
	`oiid` INT UNSIGNED AUTO_INCREMENT,
	`oname` VARCHAR(255) NOT NULL UNIQUE,
	`onumber` INT(50) NOT NULL,
    `oprice` DECIMAL(5,2) NOT NULL,
    `order_id` INT UNSIGNED,    
    PRIMARY KEY (`oiid`),
    FOREIGN KEY (order_id) REFERENCES orders (order_id) 
) ENGINE=INNODB AUTO_INCREMENT=1000 DEFAULT CHARACTER SET utf8; 


CREATE TABLE `news` (
	`nid` INT UNSIGNED AUTO_INCREMENT,
    `ntime` date NOT NULL,
    `title` VARCHAR(30) NOT NULL,
	`ncontent` VARCHAR(255) NOT NULL,
	PRIMARY KEY (`nid`)
) ENGINE=INNODB AUTO_INCREMENT=1000 DEFAULT CHARACTER SET utf8 


